services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      # Monta la carpeta local de media en el contenedor para persistencia de archivos subidos
      - ./proyecto_django/media:/app/media
      # Monta la base de datos para persistencia
      - ./proyecto_django/db.sqlite3:/app/proyecto_django/db.sqlite3
    environment:
      # Configuración para Django
      DJANGO_SETTINGS_MODULE: proyecto_django.settings.local
      DEBUG: "False"
    restart: unless-stopped
    command:
      [
        "uv",
        "run",
        "python",
        "proyecto_django/manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
