version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      # Monta la carpeta local de media en el contenedor
      - ./proyecto_django/media:/app/media
    restart: unless-stopped
