# Generated by Django 5.1.2 on 2025-06-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prenda', models.CharField(max_length=100)),
                ('color_prenda', models.CharField(max_length=50)),
                ('talla_prenda', models.CharField(max_length=10)),
                ('categoria_prenda', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prendas/')),
            ],
        ),
    ]
