# Generated by Django 5.2.3 on 2025-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_carrito_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prenda',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
